#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jul 22 10:12:49 EDT 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim serial_int_behav -key {Behavioral:sim_1:Functional:serial_int} -tclbatch serial_int.tcl -view /home/erc528/serial_int_behav.wcfg -log simulate.log"
xsim serial_int_behav -key {Behavioral:sim_1:Functional:serial_int} -tclbatch serial_int.tcl -view /home/erc528/serial_int_behav.wcfg -log simulate.log

